#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hibernate-inheritance
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
